# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets;
from PyQt5.QtGui import QMovie;
from PyQt5.QtCore import Qt


class Ui_Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)

        # hello label
        self.HelloLabel = QtWidgets.QLabel(self.centralwidget)
        self.HelloLabel.setGeometry(QtCore.QRect(20, 80, 271, 61))
        self.HelloLabel.setFont(font)
        self.HelloLabel.setStyleSheet("color:rgb(170, 170, 255)")
        self.HelloLabel.setTextFormat(QtCore.Qt.AutoText)
        self.HelloLabel.setWordWrap(True)
        self.HelloLabel.setObjectName("HelloLabel")
        self.HelloLabel.setAlignment(Qt.AlignCenter)

        # no listened label
        self.NoListenLabel = QtWidgets.QLabel(self.centralwidget)
        self.NoListenLabel.setGeometry(QtCore.QRect(60, 140, 191, 25))
        self.NoListenLabel.setFont(font)
        self.NoListenLabel.setStyleSheet("color: rgb(170, 170, 255);")
        self.NoListenLabel.setTextFormat(QtCore.Qt.AutoText)
        self.NoListenLabel.setObjectName("NoListenLabel")

        # wake up label
        self.WakeUpLabel = QtWidgets.QLabel(self.centralwidget)
        self.WakeUpLabel.setGeometry(QtCore.QRect(15, 100, 270, 25))
        self.WakeUpLabel.setFont(font)
        self.WakeUpLabel.setStyleSheet("color: rgb(170, 170, 255);")
        self.WakeUpLabel.setTextFormat(QtCore.Qt.AutoText)
        self.WakeUpLabel.setWordWrap(True)
        self.WakeUpLabel.setObjectName("WakeUpLabel")
        self.WakeUpLabel.setAlignment(Qt.AlignCenter)

        # help label
        self.HelpLabel = QtWidgets.QLabel(self.centralwidget)
        self.HelpLabel.setGeometry(QtCore.QRect(80, 280, 151, 61))
        self.HelpLabel.setFont(font)
        self.HelpLabel.setStyleSheet("color: rgb(170, 170, 255);")
        self.HelpLabel.setTextFormat(QtCore.Qt.AutoText)
        self.HelpLabel.setWordWrap(True)
        self.HelpLabel.setObjectName("HelpLabel")
        self.HelpLabel.setAlignment(Qt.AlignCenter)

        # help title label
        self.HelpTitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.HelpTitleLabel.setGeometry(QtCore.QRect(30, 70, 231, 61))
        self.HelpTitleLabel.setFont(font)
        self.HelpTitleLabel.setStyleSheet("color: rgb(170, 170, 255);")
        self.HelpTitleLabel.setWordWrap(True)
        self.HelpTitleLabel.setObjectName("HelpTitleLabel")

        # command layout
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 170, 120, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.MusicLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.MusicLabel.setGeometry(QtCore.QRect(65, 180, 180, 51))
        self.MusicLabel.setFont(font)
        self.MusicLabel.setStyleSheet("color: rgb(170, 170, 255);")
        self.MusicLabel.setWordWrap(True)
        self.MusicLabel.setObjectName("MusicLabel")
        self.verticalLayout.addWidget(self.MusicLabel)

        self.NotepadLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.NotepadLabel.setGeometry(QtCore.QRect(65, 230, 180, 51))
        self.NotepadLabel.setFont(font)
        self.NotepadLabel.setStyleSheet("color: rgb(170, 170, 255);")
        self.NotepadLabel.setWordWrap(True)
        self.NotepadLabel.setObjectName("NotepadLabel")
        self.verticalLayout.addWidget(self.NotepadLabel)

        self.BrowserLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.BrowserLabel.setGeometry(QtCore.QRect(65, 280, 180, 51))
        self.BrowserLabel.setFont(font)
        self.BrowserLabel.setStyleSheet("color: rgb(170, 170, 255);")
        self.BrowserLabel.setWordWrap(True)
        self.BrowserLabel.setObjectName("BrowserLabel")
        self.verticalLayout.addWidget(self.BrowserLabel)

        self.CalLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.CalLabel.setGeometry(QtCore.QRect(65, 330, 180, 51))
        self.CalLabel.setFont(font)
        self.CalLabel.setStyleSheet("color: rgb(170, 170, 255);")
        self.CalLabel.setWordWrap(True)
        self.CalLabel.setObjectName("CalculateLabel")
        self.verticalLayout.addWidget(self.CalLabel)

        # enjoy music label
        self.EnjoyMusicLabel = QtWidgets.QLabel(self.centralwidget)
        self.EnjoyMusicLabel.setGeometry(QtCore.QRect(55, 330, 191, 61))
        self.EnjoyMusicLabel.setFont(font)
        self.EnjoyMusicLabel.setStyleSheet("color: rgb(170, 170, 255);")
        self.EnjoyMusicLabel.setTextFormat(QtCore.Qt.AutoText)
        self.EnjoyMusicLabel.setWordWrap(True)
        self.EnjoyMusicLabel.setObjectName("HelpLabel")
        self.EnjoyMusicLabel.setAlignment(Qt.AlignCenter)

        # hint label

        self.HintLabel = QtWidgets.QLabel(self.centralwidget)
        self.HintLabel.setGeometry(QtCore.QRect(30, 100, 241, 71))
        self.HintLabel.setFont(font)
        self.HintLabel.setStyleSheet("color: rgb(170, 170, 255);")
        self.HintLabel.setWordWrap(True)
        self.HintLabel.setObjectName("HintLabel")
        self.HintLabel.setAlignment(Qt.AlignCenter)

        # gif iamge
        self.bgStatic = QMovie("assets/bg.png")
        self.MusicLogo = QMovie("assets/onMusic.gif")
        self.bgLive = QMovie("assets/bg.jpg")
        self.bgClean = QMovie("assets/bg-none.png")
        self.bgStatic.start()
        self.MusicLogo.start()
        self.bgLive.start()
        self.bgClean.start()

        # background iamge
        self.BgLabel = QtWidgets.QLabel(self.centralwidget)
        self.BgLabel.setGeometry(QtCore.QRect(0, 0, 300, 500))
        self.BgLabel.setText("")
        self.BgLabel.setMovie(self.bgStatic)
        self.BgLabel.lower()
        self.BgLabel.setScaledContents(True)
        self.BgLabel.setObjectName("LogoLabel")

        # music logo
        self.MusicLogoLabel = QtWidgets.QLabel(self.centralwidget)
        self.MusicLogoLabel.setGeometry(QtCore.QRect(0, 0, 300, 300))
        self.MusicLogoLabel.setText("")
        self.MusicLogoLabel.setMovie(self.MusicLogo)
        self.MusicLogoLabel.setVisible(False)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setFixedSize(300, 500)
        MainWindow.setWindowTitle(_translate("MainWindow", "voice"))
        self.HelloLabel.setText(_translate("MainWindow", "Say hello to wakeup me！"))
        self.NoListenLabel.setText(_translate("MainWindow", "I can't hear you！"))
        self.WakeUpLabel.setText(_translate("MainWindow", "Hi, what can I do for you?"))
        self.MusicLabel.setText(_translate("MainWindow", "1. Music"))
        self.NotepadLabel.setText(_translate("MainWindow", "2. Notepad"))
        self.BrowserLabel.setText(_translate("MainWindow", "3. Browser"))
        self.CalLabel.setText(_translate("MainWindow", "4. Calculate"))
        self.HelpTitleLabel.setText(_translate("MainWindow", "Command you can say\nis below:"))
        self.HelpLabel.setText(_translate("MainWindow", "Click to see command"))
        self.EnjoyMusicLabel.setText(_translate("MainWindow", "Playing music now\nenjoy it until finish!"))
        self.HintLabel.setText(_translate("MainWindow", "I got it!\nwait a moment..."))
        self.HelpTitleLabel.setVisible(False)
        self.verticalLayoutWidget.setVisible(False)
        self.EnjoyMusicLabel.setVisible(False)
        self.NoListenLabel.setVisible(False)
        self.WakeUpLabel.setVisible(False)
        self.HintLabel.setVisible(False)
        self.HelpLabel.setVisible(True)
